### ISSUE TITLE
[BUG] yarn build fails

### ISSUE THREAD

**Issue by jmsunseri** [lmmfranco/nintendo-switch-eshop#471] opened 2021-06-18 06:09 UTC
**Please describe the problem you are having in as much detail as possible:**

running yarn build fails with the following error

```
Using @sveltejs/adapter-vercel
 > node_modules/nintendo-switch-eshop/dist/index.mjs:15:13: error: The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)
    15 │ export const __esModule = mod.__esModule;
       ╵              ~~~~~~~~~~

> Build failed with 1 error:
node_modules/nintendo-switch-eshop/dist/index.mjs:15:13: error: The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)
Error: Build failed with 1 error:
node_modules/nintendo-switch-eshop/dist/index.mjs:15:13: error: The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)
    at failureErrorWithLog (/Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:1449:15)
    at /Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:1049:65)
    at buildResponseToResult (/Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:1236:14
    at /Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/jmsunseri/dev/code/n-buddy/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/dev/code/n-buddy(master) » 
```

**Comment by Favna** [comment] 2021-06-18 21:09
This was actually an issue in esbuild which was caused by gen-esm-wrapper rather than this library specifically. That said, as it happens it was also recently fixed in gen-esm-wrapper (https://github.com/addaleax/gen-esm-wrapper/pull/7) so I'm momentarily publishing v5.1.1 which will have the `__esModule` key removed.

**Closed** 2021-06-18 21:08 UTC
Labels: Bug: Unverified

**Comment by Favna** [comment] 2021-06-18 21:48
Version 6.0.0 has been published fixing this issue: https://github.com/lmmfranco/nintendo-switch-eshop/releases/tag/v6.0.0
