### ISSUE TITLE
Question:  no HongKong store in getActiveShops

### ISSUE THREAD

**Issue by JokerPeter** [lmmfranco/nintendo-switch-eshop#267] opened 2020-10-06 06:27 UTC
in getActiveShops found not HongKong。

**Comment by Favna** [comment] 2020-10-06 06:49
This library only supports American, European and Japanese eShops and no further storefronts are planned to be added by me. If you're willing to then you're free to make a pull request to add HK support.

Also duplicate of #254.

**Closed** 2020-10-06 06:51 UTC
Labels: Type: Question
